const countrySelect = document.getElementById('country-select');
const stateSelect = document.getElementById('state-select');
const lgaSelect = document.getElementById('lga-select');

// Define states and LGAs for Nigeria
const nigeriaStates = [
    { id: 1, name: 'Abia' },
    { id: 2, name: 'Adamawa' },
    { id: 3, name: 'Akwa Ibom' },
    { id: 4, name: 'Anambra' },
    { id: 5, name: 'Bauchi' },
    { id: 6, name: 'Bayelsa' },
    { id: 7, name: 'Benue' },
    { id: 8, name: 'Borno' },
    { id: 9, name: 'Cross River' },
    { id: 10, name: 'Delta' },
    { id: 11, name: 'Ebonyi' },
    { id: 12, name: 'Edo' },
    { id: 13, name: 'Ekiti' },
    { id: 14, name: 'Enugu' },
    { id: 15, name: 'Gombe' },
    { id: 16, name: 'Imo' },
    { id: 17, name: 'Jigawa' },
    { id: 18, name: 'Kaduna' },
    { id: 19, name: 'Kano' },
    { id: 20, name: 'Katsina' },
    { id: 21, name: 'Kebbi' },
    { id: 22, name: 'Kogi' },
    { id: 23, name: 'Kwara' },
    { id: 24, name: 'Lagos' },
    { id: 25, name: 'Nasarawa' },
    { id: 26, name: 'Niger' },
    { id: 27, name: 'Ogun' },
    { id: 28, name: 'Ondo' },
    { id: 29, name: 'Osun' },
    { id: 30, name: 'Oyo' },
    { id: 31, name: 'Plateau' },
    { id: 32, name: 'Rivers' },
    { id: 33, name: 'Sokoto' },
    { id: 34, name: 'Taraba' },
    { id: 35, name: 'Yobe' },
    { id: 36, name: 'Zamfara'},
    { id: 37, name: 'FCT Abuja'}
  ];

    const nigeriaLgas = {
            1: [
              { id: 1, name: 'Aba North' },
              { id: 2, name: 'Aba South' },
              { id: 3, name: 'Arochukwu' },
              { id: 4, name: 'Bende' },
              { id: 5, name: 'Ikwuano' },
              { id: 6, name: 'Isiala Ngwa North' },
              { id: 7, name: 'Isiala Ngwa South' },
              { id: 8, name: 'Isuikwuato' },
              { id: 9, name: 'Obi Ngwa' },
              { id: 10, name: 'Ohafia' },
              { id: 11, name: 'Osisioma' },
              { id: 12, name: 'Ugwunagbo' },
              { id: 13, name: 'Ukwa East' },
              { id: 14, name: 'Ukwa West' },
              { id: 15, name: 'Umuahia North' },
              { id: 16, name: 'Umuahia South' },
              { id: 17, name: 'Umunneochi' }
            ],
            2: [
              { id: 1, name: 'Demsa' },
              { id: 2, name: 'Fufore' },
              { id: 3, name: 'Ganye' },
              { id: 4, name: 'Girei' },
              { id: 5, name: 'Gireri' },
              { id: 6, name: 'Hong' },
              { id: 7, name: 'Jada' },
              { id: 8, name: 'Lamurde' },
              { id: 9, name: 'Mayo Belwa' },
              { id: 10, name: 'Michika' },
              { id: 11, name: 'Mubi North' },
              { id: 12, name: 'Mubi South' },
              { id: 13, name: 'Numan' },
              { id: 14, name: 'Shelleng' },
              { id: 15, name: 'Song' },
              { id: 16, name: 'Toungo' },
              { id: 17, name: 'Yola North' },
              { id: 18, name: 'Yola South' }
            ],
            3: [
              { id: 1, name: 'Abak' },
              { id: 2, name: 'Eastern Obolo' },
              { id: 3, name: 'Ekidikang' },
              { id: 4, name: 'Essien Udim' },
              { id: 5, name: 'Ibesikpo Asutan' },
              { id: 6, name: 'Ibiono Ibom' },
              { id: 7, name: 'Ikwuano' },
              { id: 8, name: 'Ikot Abasi' },
              { id: 9, name: 'Ikot Ekpene' },
              { id: 10, name: 'Ini' },
              { id: 11, name: 'Itu' },
              { id: 12, name: 'Mbo' },
              { id: 13, name: 'Mkpat Enin' },
              { id: 14, name: 'Nsit Atai' },
              { id: 15, name: 'Nsit Ibom' },
              { id: 16, name: 'Nsit Ubi' },
              { id: 17, name: 'Obot Akara' },
              { id: 18, name: 'Okobo' },
              { id: 19, name: 'Oruk Anam' },
              { id: 20, name: 'Uruan' },
              { id: 21, name: 'Uyo' }
            ],
            4: [
              { id: 1, name: 'Aguata' },
              { id: 2, name: 'Anambra East' },
              { id: 3, name: 'Anambra West' },
              { id: 4, name: 'Awka North' },
              { id: 5, name: 'Awka South' },
              { id: 6, name: 'Dunukofia' },
              { id: 7, name: 'Ekwusigo' },
              { id: 8, name: 'Idemili North' },
              { id: 9, name: 'Idemili South' },
              { id: 10, name: 'Ihiala' },
              { id: 11, name: 'Njikoka' },
              { id: 12, name: 'Nnewi North' },
              { id: 13, name: 'Nnewi South' },
              { id: 14, name: 'Ogbaru' },
              { id: 15, name: 'Onitsha North' },
              { id: 16, name: 'Onitsha South' },
              { id: 17, name: 'Orumba North' },
              { id: 18, name: 'Orumba South' }
            ],
            5: [
              { id: 1, name: 'Alkaleri' },
              { id: 2, name: 'Bauchi' },
              { id: 3, name: 'Bogoro' },
              { id: 4, name: 'Damban' },
              { id: 5, name: 'Darazo' },
              { id: 6, name: 'Dass' },
              { id: 7, name: 'Gamawa' },
              { id: 8, name: 'Ganjuwa' },
              { id: 9, name: 'Giade' },
              { id: 10, name: 'Jama’are' },
              { id: 11, name: 'Katagum' },
              { id: 12, name: 'Kirfi' },
              { id: 13, name: 'Misau' },
              { id: 14, name: 'Ningi' },
              { id: 15, name: 'Shira' },
              { id: 16, name: 'Tafawa Balewa' },
              { id: 17, name: 'Toro' },
              { id: 18, name: 'Warji' },
              { id: 19, name: 'Zaki' }
            ],
            6: [
              { id: 1, name: 'Brass' },
              { id: 2, name: 'Ekeremor' },
              { id: 3, name: 'Kolokuma/Opokuma' },
              { id: 4, name: 'Nembe' },
              { id: 5, name: 'Ogbia' },
              { id: 6, name: 'Sagbama' },
              { id: 7, name: 'Southern Ijaw' },
              { id: 8, name: 'Yenagoa' }
            ],
            7: [
                { id: 1, name: 'Ado' },
                { id: 2, name: 'Agatu' },
                { id: 3, name: 'Apa' },
                { id: 4, name: 'Buruku' },
                { id: 5, name: 'Gboko' },
                { id: 6, name: 'Guma' },
                { id: 7, name: 'Gwer East' },
                { id: 8, name: 'Gwer West' },
                { id: 9, name: 'Katsina-Ala' },
                { id: 10, name: 'Konshisha' },
                { id: 11, name: 'Kwande' },
                { id: 12, name: 'Logo' },
                { id: 13, name: 'Makurdi' },
                { id: 14, name: 'Ogbadibo' },
                { id: 15, name: 'Ohimini' },
                { id: 16, name: 'Obi' },
                { id: 17, name: 'Tarka' },
                { id: 18, name: 'Vandeikya' }
              ],
              8: [
                { id: 1, name: 'Abadam' },
                { id: 2, name: 'Askira/Uba' },
                { id: 3, name: 'Bama' },
                { id: 4, name: 'Bayo' },
                { id: 5, name: 'Birniwa' },
                { id: 6, name: 'Chibok' },
                { id: 7, name: 'Dikwa' },
                { id: 8, name: 'Gubio' },
                { id: 9, name: 'Gwoza' },
                { id: 10, name: 'Hawul' },
                { id: 11, name: 'Jere' },
                { id: 12, name: 'Kaga' },
                { id: 13, name: 'Konduga' },
                { id: 14, name: 'Kukawa' },
                { id: 15, name: 'Mafa' },
                { id: 16, name: 'Maiduguri' },
                { id: 17, name: 'Shani' }
              ],
              9: [
                { id: 1, name: 'Akpabuyo' },
                { id: 2, name: 'Biase' },
                { id: 3, name: 'Boki' },
                { id: 4, name: 'Calabar Municipal' },
                { id: 5, name: 'Calabar South' },
                { id: 6, name: 'Etung' },
                { id: 7, name: 'Ikom' },
                { id: 8, name: 'Obanliku' },
                { id: 9, name: 'Obubra' },
                { id: 10, name: 'Odukpani' },
                { id: 11, name: 'Ogoja' },
                { id: 12, name: 'Yakuur' },
                { id: 13, name: 'Bekwarra' }
              ],
              10: [
                { id: 1, name: 'Aniocha North' },
                { id: 2, name: 'Aniocha South' },
                { id: 3, name: 'Bomadi' },
                { id: 4, name: 'Burutu' },
                { id: 5, name: 'Ethiope East' },
                { id: 6, name: 'Ethiope West' },
                { id: 7, name: 'Ika North East' },
                { id: 8, name: 'Ika South' },
                { id: 9, name: 'Isoko North' },
                { id: 10, name: 'Isoko South' },
                { id: 11, name: 'Ndokwa East' },
                { id: 12, name: 'Ndokwa West' },
                { id: 13, name: 'Okpe' },
                { id: 14, name: 'Oshimili North' },
                { id: 15, name: 'Oshimili South' },
                { id: 16, name: 'Patani' },
                { id: 17, name: 'Sapele' },
                { id: 18, name: 'Udu' },
                { id: 19, name: 'Ughelli North' },
                { id: 20, name: 'Ughelli South' },
                { id: 21, name: 'Ukwuani' },
                { id: 22, name: 'Warri North' },
                { id: 23, name: 'Warri South' },
                { id: 24, name: 'Warri South West' }
              ],
              11: [
                { id: 1, name: 'Abakaliki' },
                { id: 2, name: 'Afikpo North' },
                { id: 3, name: 'Afikpo South' },
                { id: 4, name: 'Ishielu' },
                { id: 5, name: 'Ivo' },
                { id: 6, name: 'Izzi' },
                { id: 7, name: 'Ohaozara' },
                { id: 8, name: 'Ohaukwu' },
                { id: 9, name: 'Onicha' }
              ],
              12: [
                { id: 1, name: 'Akoko-Edo' },
                { id: 2, name: 'Egor' },
                { id: 3, name: 'Esan Central' },
                { id: 4, name: 'Esan North-East' },
                { id: 5, name: 'Esan South-East' },
                { id: 6, name: 'Igueben' },
                { id: 7, name: 'Ikpoba-Okha' },
                { id: 8, name: 'Oredo' },
                { id: 9, name: 'Orhionmwon' },
                { id: 10, name: 'Ovia North-East' },
                { id: 11, name: 'Ovia South-West' },
                { id: 12, name: 'Uhunmwonde' }
              ],
              13: [
                { id: 1, name: 'Ado Ekiti' },
                { id: 2, name: 'Efon' },
                { id: 3, name: 'Ekiti East' },
                { id: 4, name: 'Ekiti South-West' },
                { id: 5, name: 'Ekiti West' },
                { id: 6, name: 'Emure' },
                { id: 7, name: 'Gbonyin' },
                { id: 8, name: 'Ido Osi' },
                { id: 9, name: 'Ijero' },
                { id: 10, name: 'Ikere' },
                { id: 11, name: 'Ilejemeje' },
                { id: 12, name: 'Irepodun/Ifelodun' },
                { id: 13, name: 'Ise/Orun' },
                { id: 14, name: 'Moba' },
                { id: 15, name: 'Oye' }
              ],
              14: [
                { id: 1, name: 'Aninri' },
                { id: 2, name: 'Awgu' },
                { id: 3, name: 'Enugu East' },
                { id: 4, name: 'Enugu North' },
                { id: 5, name: 'Enugu South' },
                { id: 6, name: 'Ezeagu' },
                { id: 7, name: 'Igbo-Etiti' },
                { id: 8, name: 'Igboetiti' },
                { id: 9, name: 'Isi-Uzo' },
                { id: 10, name: 'Nkanu East' },
                { id: 11, name: 'Nkanu West' },
                { id: 12, name: 'Nsukka' },
                { id: 13, name: 'Oji-River' },
                { id: 14, name: 'Udenu' },
                { id: 15, name: 'Udi' },
                { id: 16, name: 'Uzo-Uwani' }
              ],
              15: [
                { id: 1, name: 'Akko' },
                { id: 2, name: 'Balanga' },
                { id: 3, name: 'Billiri' },
                { id: 4, name: 'Dukku' },
                { id: 5, name: 'Funakaye' },
                { id: 6, name: 'Gombe' },
                { id: 7, name: 'Kaltungo' },
                { id: 8, name: 'Kwami' },
                { id: 9, name: 'Nafada' },
                { id: 10, name: 'Shongom' },
                { id: 11, name: 'Yamaltu/Deba' }
              ],
              16: [
                { id: 1, name: 'Aboh Mbaise' },
                { id: 2, name: 'Ahiazu Mbaise' },
                { id: 3, name: 'Ebonyi' },
                { id: 4, name: 'Ehime Mbano' },
                { id: 5, name: 'Ihitte/Uboma' },
                { id: 6, name: 'Ikeduru' },
                { id: 7, name: 'Isu' },
                { id: 8, name: 'Mbaitoli' },
                { id: 9, name: 'Ngor Okpala' },
                { id: 10, name: 'Njaba' },
                { id: 11, name: 'Nwangele' },
                { id: 12, name: 'Obowo' },
                { id: 13, name: 'Oguta' },
                { id: 14, name: 'Ohaji/Egbema' },
                { id: 15, name: 'Orlu' },
                { id: 16, name: 'Oru East' },
                { id: 17, name: 'Oru West' },
                { id: 18, name: 'Ukwuani' },
                { id: 19, name: 'Umuchima' }
              ],
              17: [
                { id: 1, name: 'Auyo' },
                { id: 2, name: 'Babura' },
                { id: 3, name: 'Birnin Kudu' },
                { id: 4, name: 'Buji' },
                { id: 5, name: 'Dutse' },
                { id: 6, name: 'Gagarawa' },
                { id: 7, name: 'Garki' },
                { id: 8, name: 'Gumel' },
                { id: 9, name: 'Hadejia' },
                { id: 10, name: 'Kafin Hausa' },
                { id: 11, name: 'Kaugama' },
                { id: 12, name: 'Kazaure' },
                { id: 13, name: 'Kiri Kasama' },
                { id: 14, name: 'Maigatari' },
                { id: 15, name: 'Malam Madori' },
                { id: 16, name: 'Miga' },
                { id: 17, name: 'Ringim' },
                { id: 18, name: 'Roni' },
                { id: 19, name: 'Sule Tankarkar' },
                { id: 20, name: 'Taura' },
                { id: 21, name: 'Yankwashi' }
              ],
              18: [
                { id: 1, name: 'Birnin Gwari' },
                { id: 2, name: 'Chikun' },
                { id: 3, name: 'Giwa' },
                { id: 4, name: 'Igabi' },
                { id: 5, name: 'Ikara' },
                { id: 6, name: 'Jaba' },
                { id: 7, name: 'Jema\'a' },
                { id: 8, name: 'Kachia' },
                { id: 9, name: 'Kaduna North' },
                { id: 10, name: 'Kaduna South' },
                { id: 11, name: 'Kagarko' },
                { id: 12, name: 'Kajuru' },
                { id: 13, name: 'Lere' },
                { id: 14, name: 'Makarfi' },
                { id: 15, name: 'Sabon Gari' },
                { id: 16, name: 'Sanga' },
                { id: 17, name: 'Soba' },
                { id: 18, name: 'Zangon Kataf' },
                { id: 19, name: 'Zaria' }
              ],
              19: [
                { id: 1, name: 'Ajingi' },
                { id: 2, name: 'Albasu' },
                { id: 3, name: 'Bagwai' },
                { id: 4, name: 'Bebeji' },
                { id: 5, name: 'Bichi' },
                { id: 6, name: 'Bunkure' },
                { id: 7, name: 'Dala' },
                { id: 8, name: 'Dambatta' },
                { id: 9, name: 'Dawakin Kudu' },
                { id: 10, name: 'Dawakin Tofa' },
                { id: 11, name: 'Doguwa' },
                { id: 12, name: 'Fagge' },
                { id: 13, name: 'Gabasawa' },
                { id: 14, name: 'Garko' },
                { id: 15, name: 'Garun Mallam' },
                { id: 16, name: 'Gezawa' },
                { id: 17, name: 'Gaya' },
                { id: 18, name: 'Kabo' },
                { id: 19, name: 'Kano Municipal' },
                { id: 20, name: 'Karaye' },
                { id: 21, name: 'Kibiya' },
                { id: 22, name: 'Kiru' },
                { id: 23, name: 'Kumbotso' },
                { id: 24, name: 'Kunchi' },
                { id: 25, name: 'Kura' },
                { id: 26, name: 'Madobi' },
                { id: 27, name: 'Makoda' },
                { id: 28, name: 'Minjibir' },
                { id: 29, name: 'Nassarawa' },
                { id: 30, name: 'Rano' },
                { id: 31, name: 'Rimin Gado' },
                { id: 32, name: 'Rosy' },
                { id: 33, name: 'Tudun Wada' }
              ],
              20: [
                { id: 1, name: 'Baure' },
                { id: 2, name: 'Bindawa' },
                { id: 3, name: 'Charanchi' },
                { id: 4, name: 'Dandume' },
                { id: 5, name: 'Dan Musa' },
                { id: 6, name: 'Daura' },
                { id: 7, name: 'Funtua' },
                { id: 8, name: 'Jibia' },
                { id: 9, name: 'Kaita' },
                { id: 10, name: 'Kankara' },
                { id: 11, name: 'Katsina' },
                { id: 12, name: 'Kurfi' },
                { id: 13, name: 'Mai\'aduwa' },
                { id: 14, name: 'Malumfashi' },
                { id: 15, name: 'Mani' },
                { id: 16, name: 'Mashi' },
                { id: 17, name: 'Musawa' },
                { id: 18, name: 'Rimi' },
                { id: 19, name: 'Sabuwa' },
                { id: 20, name: 'Safana' },
                { id: 21, name: 'Sandamu' },
                { id: 22, name: 'Zango' }
              ],
              21: [
                { id: 1, name: 'Arewa Dandi' },
                { id: 2, name: 'Argungu' },
                { id: 3, name: 'Augie' },
                { id: 4, name: 'Bagudo' },
                { id: 5, name: 'Birnin Kebbi' },
                { id: 6, name: 'Dandi' },
                { id: 7, name: 'Fakai' },
                { id: 8, name: 'Gwandu' },
                { id: 9, name: 'Jega' },
                { id: 10, name: 'Kalgo' },
                { id: 11, name: 'Koko/Besse' },
                { id: 12, name: 'Maiyama' },
                { id: 13, name: 'Ngaski' },
                { id: 14, name: 'Sakaba' },
                { id: 15, name: 'Shanga' },
                { id: 16, name: 'Suru' },
                { id: 17, name: 'Warrah' }
              ],
              22: [
                { id: 1, name: 'Adavi' },
                { id: 2, name: 'Ajao' },
                { id: 3, name: 'Akpaja' },
                { id: 4, name: 'Bassa' },
                { id: 5, name: 'Dekina' },
                { id: 6, name: 'Ibaji' },
                { id: 7, name: 'Igalamela-Odolu' },
                { id: 8, name: 'Ijumu' },
                { id: 9, name: 'Kabba/Bunu' },
                { id: 10, name: 'Kogi' },
                { id: 11, name: 'Lokoja' },
                { id: 12, name: 'Mopa-Muro' },
                { id: 13, name: 'Ofu' },
                { id: 14, name: 'Ogori/Mangongo' },
                { id: 15, name: 'Okehi' },
                { id: 16, name: 'Okene' },
                { id: 17, name: 'Olamaboro' },
                { id: 18, name: 'Yagba East' },
                { id: 19, name: 'Yagba West' }
              ],
              23: [
                { id: 1, name: 'Asa' },
                { id: 2, name: 'Baruten' },
                { id: 3, name: 'Ekiti' },
                { id: 4, name: 'Ifelodun' },
                { id: 5, name: 'Ilorin East' },
                { id: 6, name: 'Ilorin South' },
                { id: 7, name: 'Ilorin West' },
                { id: 8, name: 'Irepodun' },
                { id: 9, name: 'Isin' },
                { id: 10, name: 'Kaiama' },
                { id: 11, name: 'Moro' },
                { id: 12, name: 'Oke-Ero' },
                { id: 13, name: 'Opoku' },
                { id: 14, name: 'Oyun' },
                { id: 15, name: 'Pategi' }
              ],
              24: [
                { id: 1, name: 'Agege' },
                { id: 2, name: 'Ajeromi-Ifelodun' },
                { id: 3, name: 'Alimosho' },
                { id: 4, name: 'Amuwo-Odofin' },
                { id: 5, name: 'Apapa' },
                { id: 6, name: 'Badagry' },
                { id: 7, name: 'Epe' },
                { id: 8, name: 'Eti-Osa' },
                { id: 9, name: 'Ibeju-Lekki' },
                { id: 10, name: 'Ifako-Ijaiye' },
                { id: 11, name: 'Ikeja' },
                { id: 12, name: 'Kosofe' },
                { id: 13, name: 'Mushin' },
                { id: 14, name: 'Ojo' },
                { id: 15, name: 'Oshodi-Isolo' },
                { id: 16, name: 'Shomolu' },
                { id: 17, name: 'Surulere' }
              ],
              25: [
                { id: 1, name: 'Akwanga' },
                { id: 2, name: 'Akure' },
                { id: 3, name: 'Doma' },
                { id: 4, name: 'Karu' },
                { id: 5, name: 'Keana' },
                { id: 6, name: 'Keffi' },
                { id: 7, name: 'Nasarawa' },
                { id: 8, name: 'Nigerian' },
                { id: 9, name: 'Obi' },
                { id: 10, name: 'Toto' }
              ],
              26: [
                { id: 1, name: 'Agaie' },
                { id: 2, name: 'Bida' },
                { id: 3, name: 'Borgu' },
                { id: 4, name: 'Chanchaga' },
                { id: 5, name: 'Edati' },
                { id: 6, name: 'Gbako' },
                { id: 7, name: 'Katcha' },
                { id: 8, name: 'Lapai' },
                { id: 9, name: 'Lavun' },
                { id: 10, name: 'Magama' },
                { id: 11, name: 'Mariga' },
                { id: 12, name: 'Mokwa' },
                { id: 13, name: 'Rafi' },
                { id: 14, name: 'Shiroro' },
                { id: 15, name: 'Suleja' }
              ],
              27: [
                { id: 1, name: 'Abeokuta North' },
                { id: 2, name: 'Abeokuta South' },
                { id: 3, name: 'Ado-Odo/Ota' },
                { id: 4, name: 'Ewekoro' },
                { id: 5, name: 'Ifo' },
                { id: 6, name: 'Ijebu East' },
                { id: 7, name: 'Ijebu North' },
                { id: 8, name: 'Ijebu North East' },
                { id: 9, name: 'Ijebu Ode' },
                { id: 10, name: 'Ikenne' },
                { id: 11, name: 'Imeko/Afon' },
                { id: 12, name: 'Ipokia' },
                { id: 13, name: 'Obafemi-Owode' },
                { id: 14, name: 'Odogbolu' },
                { id: 15, name: 'Ogun Waterside' },
                { id: 16, name: 'Odeda' },
                { id: 17, name: 'Ogun Central' }
              ],
              28: [
                { id: 1, name: 'Akoko North East' },
                { id: 2, name: 'Akoko North West' },
                { id: 3, name: 'Akoko South Akure North' },
                { id: 4, name: 'Akoko South West' },
                { id: 5, name: 'Akure South' },
                { id: 6, name: 'Ese Odo' },
                { id: 7, name: 'Idanre' },
                { id: 8, name: 'Ifedore' },
                { id: 9, name: 'Ilaje' },
                { id: 10, name: 'Ile-Oluji/Okeigbo' },
                { id: 11, name: 'Odigbo' },
                { id: 12, name: 'Ondo East' },
                { id: 13, name: 'Ondo West' },
                { id: 14, name: 'Ose' },
                { id: 15, name: 'Owo' }
              ],
              29: [
                { id: 1, name: 'Atakunmosa East' },
                { id: 2, name: 'Atakunmosa West' },
                { id: 3, name: 'Boluwaduro' },
                { id: 4, name: 'Boripe' },
                { id: 5, name: 'Ede North' },
                { id: 6, name: 'Ede South' },
                { id: 7, name: 'Egbedore' },
                { id: 8, name: 'Ife Central' },
                { id: 9, name: 'Ife East' },
                { id: 10, name: 'Ife North' },
                { id: 11, name: 'Ife South' },
                { id: 12, name: 'Ilesa East' },
                { id: 13, name: 'Ilesa West' },
                { id: 14, name: 'Irepodun' },
                { id: 15, name: 'Isokan' },
                { id: 16, name: 'Iwo' },
                { id: 17, name: 'Obokun' },
                { id: 18, name: 'Ola Oluwa' },
                { id: 19, name: 'Olorunda' },
                { id: 20, name: 'Osogbo' }
              ],
              30: [
                { id: 1, name: 'Afijio' },
                { id: 2, name: 'Akinyele' },
                { id: 3, name: 'Atiba' },
                { id: 4, name: 'Atisbo' },
                { id: 5, name: 'Egbeda' },
                { id: 6, name: 'Ibadan North' },
                { id: 7, name: 'Ibadan North-East' },
                { id: 8, name: 'Ibadan North-West' },
                { id: 9, name: 'Ibadan South-East' },
                { id: 10, name: 'Ibadan South-West' },
                { id: 11, name: 'Ibarapa Central' },
                { id: 12, name: 'Ibarapa East' },
                { id: 13, name: 'Ibarapa North' },
                { id: 14, name: 'Ido' },
                { id: 15, name: 'Irepo' },
                { id: 16, name: 'Iseyin' },
                { id: 17, name: 'Itesiwaju' },
                { id: 18, name: 'Iwajowa' },
                { id: 19, name: 'Kajola' },
                { id: 20, name: 'Lagelu' },
                { id: 21, name: 'Ogbomosho North' },
                { id: 22, name: 'Ogbomosho South' },
                { id: 23, name: 'Ogo Oluwa' },
                { id: 24, name: 'Olorunsogo' },
                { id: 25, name: 'Oluyole' },
                { id: 26, name: 'Ona Ara' },
                { id: 27, name: 'Orelope' },
                { id: 28, name: 'Ori Ire' },
                { id: 29, name: 'Oyo East' },
                { id: 30, name: 'Oyo West' },
                { id: 31, name: 'Saki East' },
                { id: 32, name: 'Saki West' },
                { id: 33, name: 'Surulere' }
              ],
              31: [
                { id: 1, name: 'Barkin Ladi' },
                { id: 2, name: 'Bassa' },
                { id: 3, name: 'Bokkos' },
                { id: 4, name: 'Jos East' },
                { id: 5, name: 'Jos North' },
                { id: 6, name: 'Jos South' },
                { id: 7, name: 'Kanam' },
                { id: 8, name: 'Kanke' },
                { id: 9, name: 'Langtang North' },
                { id: 10, name: 'Langtang South' },
                { id: 11, name: 'Mangu' },
                { id: 12, name: 'Mikang' },
                { id: 13, name: 'Pankshin' },
                { id: 14, name: 'Qua\'an Pan' },
                { id: 15, name: 'Riyom' },
                { id: 16, name: 'Shendam' },
                { id: 17, name: 'Wase' }
              ],
              32: [
                { id: 1, name: 'Abua/Odual' },
                { id: 2, name: 'Ahoada East' },
                { id: 3, name: 'Ahoada West' },
                { id: 4, name: 'Akuku-Toru' },
                { id: 5, name: 'Andoni' },
                { id: 6, name: 'Asari-Toru' },
                { id: 7, name: 'Bonny' },
                { id: 8, name: 'Degema' },
                { id: 9, name: 'Eleme' },
                { id: 10, name: 'Emohua' },
                { id: 11, name: 'Etche' },
                { id: 12, name: 'Gokana' },
                { id: 13, name: 'Ikwerre' },
                { id: 14, name: 'Khana' },
                { id: 15, name: 'Obio/Akpor' },
                { id: 16, name: 'Ogba/Egbema/Ndoni' },
                { id: 17, name: 'Ogu/Bolo' },
                { id: 18, name: 'Okrika' },
                { id: 19, name: 'Omuma' },
                { id: 20, name: 'Opobo/Nkoro' },
                { id: 21, name: 'Oyigbo' },
                { id: 22, name: 'Port Harcourt' },
                { id: 23, name: 'Tai' }
              ],
              33: [
                { id: 1, name: 'Binji' },
                { id: 2, name: 'Bodinga' },
                { id: 3, name: 'Dange-Shuni' },
                { id: 4, name: 'Gada' },
                { id: 5, name: 'Goronyo' },
                { id: 6, name: 'Gudu' },
                { id: 7, name: 'Gwadabawa' },
                { id: 8, name: 'Illela' },
                { id: 9, name: 'Isa' },
                { id: 10, name: 'Kebbe' },
                { id: 11, name: 'Kware' },
                { id: 12, name: 'Rabah' },
                { id: 13, name: 'Sabon Birni' },
                { id: 14, name: 'Shagari' },
                { id: 15, name: 'Silame' },
                { id: 16, name: 'Sokoto North' },
                { id: 17, name: 'Sokoto South' },
                { id: 18, name: 'Tambuwal' },
                { id: 19, name: 'Tangaza' },
                { id: 20, name: 'Tureta' },
                { id: 21, name: 'Wamako' },
                { id: 22, name: 'Wurno' },
                { id: 23, name: 'Yabo' }
              ],
              34: [
                { id: 1, name: 'Ardo Kola' },
                { id: 2, name: 'Bali' },
                { id: 3, name: 'Donga' },
                { id: 4, name: 'Gashaka' },
                { id: 5, name: 'Gassol' },
                { id: 6, name: 'Ibi' },
                { id: 7, name: 'Jalingo' },
                { id: 8, name: 'Karim Lamido' },
                { id: 9, name: 'Kurmi' },
                { id: 10, name: 'Lau' },
                { id: 11, name: 'Sardauna' },
                { id: 12, name: 'Takum' },
                { id: 13, name: 'Ussa' },
                { id: 14, name: 'Wukari' },
                { id: 15, name: 'Yorro' },
                { id: 16, name: 'Zing' }
              ],
              35: [
                { id: 1, name: 'Bade' },
                { id: 2, name: 'Bursari' },
                { id: 3, name: 'Damaturu' },
                { id: 4, name: 'Fika' },
                { id: 5, name: 'Fune' },
                { id: 6, name: 'Geidam' },
                { id: 7, name: 'Gujba' },
                { id: 8, name: 'Gulani' },
                { id: 9, name: 'Jakusko' },
                { id: 10, name: 'Karasuwa' },
                { id: 11, name: 'Machina' },
                { id: 12, name: 'Nangere' },
                { id: 13, name: 'Nguru' },
                { id: 14, name: 'Potiskum' },
                { id: 15, name: 'Tarmuwa' },
                { id: 16, name: 'Yunusari' },
                { id: 17, name: 'Yusufari' }
              ],
              36: [
                { id: 1, name: 'Anka' },
                { id: 2, name: 'Bakura' },
                { id: 3, name: 'Birnin Magaji/Kiyaw' },
                { id: 4, name: 'Bukkuyum' },
                { id: 5, name: 'Bungudu' },
                { id: 6, name: 'Gummi' },
                { id: 7, name: 'Gusau' },
                { id: 8, name: 'Kaura Namoda' },
                { id: 9, name: 'Maradun' },
                { id: 10, name: 'Maru' },
                { id: 11, name: 'Shinkafi' },
                { id: 12, name: 'Talata Mafara' },
                { id: 13, name: 'Chafe' },
                { id: 14, name: 'Zurmi' }
              ],
              37: [
                { id: 1, name: 'Abaji' },
                { id: 2, name: 'Bwari' },
                { id: 3, name: 'Gwagwalada' },
                { id: 4, name: 'Kuje' },
                { id: 5, name: 'Kwali' },
                { id: 6, name: 'Municipal Area Council (AMAC)' }
              ]
      };
      
// Event listener for country select
countrySelect.addEventListener('change', (e) => {
    const selectedCountry = e.target.value;
  
    if (selectedCountry === 'Nigeria') {
      // Populate states for Nigeria
      nigeriaStates.forEach((state) => {
        const option = document.createElement('option');
        option.value = state.id;
        option.text = state.name;
        stateSelect.appendChild(option)
         
      })
     
      // Enable state select
      stateSelect.disabled = false;
    } else {
      // Clear states and LGAs
      stateSelect.innerHTML = '<<option value="">Select State</option>>';
      lgaSelect.innerHTML = '<option value="">Select LGA</option>';
  
      // Disable state select
      stateSelect.disabled = true;
  
      // Allow user to type in state and LGA
      stateSelect.type = 'text';
      lgaSelect.type = 'text';
    }
  });
  

  
// Event listener for state select
stateSelect.addEventListener('change', (e) => {
    const selectedStateId = e.target.value;
  
    if (selectedStateId !== '') {
      // Populate LGAs for selected state
      nigeriaLgas[selectedStateId].forEach((lga) => {
        const option = document.createElement('option');
        option.value = lga.id;
        option.text = lga.name;
        lgaSelect.appendChild(option);
      });
  
      // Enable LGA select
      lgaSelect.disabled = false;
    } else {
      // Clear LGAs
      lgaSelect.innerHTML = '<option value="">Select LGA</option>';
  
      // Disable LGA select
      lgaSelect.disabled = true;
    }
  });
  
  


